#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
clang_format="/usr/local/bin/clang-format"
pwd

if [[ ! -x "$clang_format" ]]; then
  printf "\t\033[41mPlease install clang_format\033[0m (npm install eslint)\n"
  exit 1
fi

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(h|m|mm)$'))

echo "clang_format'ing ${#STAGED_FILES[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$clang_format -i -style=file "${STAGED_FILES[@]}"

LINT_EXIT="$?"

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

if [[ "${LINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix lint errors and try again\n"
  exit 1
fi

exit $?