# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAppWithCocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAppWithCocoaPods
  pod 'RadarSDK', :path => '../../radar-sdk-ios', :tag => '3.3.1-beta.1'
end
