name: Xcode - Build, Analyze, & Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          # Org level secret
          token: ${{ secrets.SUBMODULESTOKEN }}

      - name: Use Xcode 26.3
        run: sudo xcode-select -switch /Applications/Xcode_26.3.app

      - name: Lint Swift
        run: |
          if ! command -v swiftlint >/dev/null; then
            brew install swiftlint
          fi
          swiftlint lint --strict --baseline .swiftlint-baseline.json

      - name: Format Swift
        run: |
          git fetch origin master --depth=1
          if ! command -v swift-format >/dev/null; then
            brew install swift-format
          fi
          make format-check

      - name: Pick an available iPhone simulator
        id: pick_sim
        run: |
          # Get a UDID for a valid iPhone simulator only (exclude iPads, Apple Watch, tvOS, etc)
          SIM_ID=$(xcrun simctl list devices --json \
            | jq -r '
                .devices
                | to_entries
                # Filter keys for iOS runtimes only (ignore tvOS/watchOS)
                | map(select(.key | startswith("com.apple.CoreSimulator.SimRuntime.iOS")))
                | .[]
                .value[]
                # Only devices available AND name contains "iPhone"
                | select(.isAvailable == true and (.name | test("iPhone")))
                .udid
            ' | head -n 1)

          if [ -z "$SIM_ID" ]; then
            echo "No available iPhone simulator found"
            exit 1
          fi

          echo "SIMULATOR_ID=$SIM_ID" >> $GITHUB_ENV
          echo "Picked iPhone simulator UDID: $SIM_ID"

      - name: Build and Analyze
        env:
          SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
          scheme: RadarSDK
        run: |
          make ci-build-analyze CI_DESTINATION="platform=iOS Simulator,id=${SIMULATOR_ID}"

      - name: Test
        env:
          SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
          scheme: RadarSDK
        run: |
          make ci-test-pretty CI_DESTINATION="platform=iOS Simulator,id=${SIMULATOR_ID}"
        
      - name: Test swift
        env:
          SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
          scheme: RadarSDK
        run: |
          make ci-test-swift CI_DESTINATION="platform=iOS Simulator,id=${SIMULATOR_ID}"

      - name: Build example app
        env:
          SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
        run: |
          make ci-build-example CI_DESTINATION="platform=iOS Simulator,id=${SIMULATOR_ID}"

      - name: Lint podspecs
        run: make lint
