# When a new release is created on GitHub, this workflow sends an event
# to cross-platform SDK repos that depend on native iOS SDK
name: Downstream version bump
on:
  # Triggered when a new release is tagged in GitHub.
  release:
    types: [ released ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      matrix:
        repo: [
          'radarlabs/react-native-radar',
          'radarlabs/capacitor-radar',
          'radarlabs/flutter-radar',
          'radarlabs/radar-sdk-xamarin',
          'radarlabs/cordova-plugin-radar',
        ]
    runs-on: macos-latest
    steps:
      - name: Dispatch to downtream SDKs
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.RADAR_CIRCLECI_PAT }}
          repository: ${{ matrix.repo }}
          event-type: ios-sdk-release
          client-payload: '{"release": "${{ github.event.release.tag_name }}", "platform": "ios"}'
